In [35]:

import pandas as pd
import matplotlib
import requests
import io
import numpy as np
url = "https://raw.githubusercontent.com/mich-matocha/data-therapy/main/data/QA_2016.T.csv"
url_content = requests.get(url).text

#with open()
data = pd.read_csv(url,encoding='utf-8')

data.head()

,UserID,1,2,3,4,5,6,7,8,9,...,109,110,111,112,113,114,115,116,117,118
0,1261,39,Male,United Kingdom,-1,0,No,0,26-100,1,...,None of them,Some of my previous employers,I don't know,None of them,Maybe,"No, I don't think they would",-1,-1,Back-end Developer,Sometimes
1,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Anxiety Disorder (Generalized, Social, Phobia,...",-1,Back-end Developer,Never
2,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Anxiety Disorder (Generalized, Social, Phobia,...",-1,Front-end Developer,Never
3,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Mood Disorder (Depression, Bipolar Disorder, etc)",-1,Back-end Developer,Never
4,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Mood Disorder (Depression, Bipolar Disorder, etc)",-1,Front-end Developer,Never

In [27]:
data = data.replace('-1',np.NaN) #?
data.head()

,UserID,1,2,3,4,5,6,7,8,9,...,109,110,111,112,113,114,115,116,117,118
0,1261,39,Male,United Kingdom,NaN,0,No,0,26-100,1,...,None of them,Some of my previous employers,I don't know,None of them,Maybe,"No, I don't think they would",NaN,NaN,Back-end Developer,Sometimes
1,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Anxiety Disorder (Generalized, Social, Phobia,...",NaN,Back-end Developer,Never
2,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Anxiety Disorder (Generalized, Social, Phobia,...",NaN,Front-end Developer,Never
3,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,Back-end Developer,Never
4,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,Front-end Developer,Never

In [36]:
index = 0
for row in data['3']:
    if row != 'United States of America':
        data.drop(index=index,inplace=True)
    index += 1
data.head()

,UserID,1,2,3,4,5,6,7,8,9,...,109,110,111,112,113,114,115,116,117,118
1,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Anxiety Disorder (Generalized, Social, Phobia,...",-1,Back-end Developer,Never
2,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Anxiety Disorder (Generalized, Social, Phobia,...",-1,Front-end Developer,Never
3,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Mood Disorder (Depression, Bipolar Disorder, etc)",-1,Back-end Developer,Never
4,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Mood Disorder (Depression, Bipolar Disorder, etc)",-1,Front-end Developer,Never
8,1265,43,Female,United States of America,Illinois,0,Yes,1,6-25,0,...,Some of them,"No, at none of my previous employers",Some did,Some of them,"Yes, I think it would",Maybe,"Anxiety Disorder (Generalized, Social, Phobia,...",-1,Executive Leadership,Sometimes

In [38]:
print('size',data.shape)
print('index',data.index)

data_index = data.index

index = 0 
for row in data['5']:
    if row == 1:
        data.drop(index=data_index[index],inplace=True)
    index += 1
print('new size',data.shape)
data.head()

size (2251, 61)
index Int64Index([   1,    2,    3,    4,    8,    9,   10,   11,   12,   13,
            ...
            4712, 4746, 4747, 4748, 4749, 4750, 4751, 4752, 4753, 4754],
           dtype='int64', length=2251)
new size (1745, 61)

,UserID,1,2,3,4,5,6,7,8,9,...,109,110,111,112,113,114,115,116,117,118
1,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Anxiety Disorder (Generalized, Social, Phobia,...",-1,Back-end Developer,Never
2,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Anxiety Disorder (Generalized, Social, Phobia,...",-1,Front-end Developer,Never
3,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Mood Disorder (Depression, Bipolar Disorder, etc)",-1,Back-end Developer,Never
4,1262,29,Male,United States of America,Illinois,0,Yes,1,6-25,1,...,None of them,"No, at none of my previous employers",Some did,None of them,"No, I don't think it would","No, I don't think they would","Mood Disorder (Depression, Bipolar Disorder, etc)",-1,Front-end Developer,Never
8,1265,43,Female,United States of America,Illinois,0,Yes,1,6-25,0,...,Some of them,"No, at none of my previous employers",Some did,Some of them,"Yes, I think it would",Maybe,"Anxiety Disorder (Generalized, Social, Phobia,...",-1,Executive Leadership,Sometimes